"""change post status names

Revision ID: 744e7e0a3943
Revises: 7f1375646d8b
Create Date: 2023-12-03 00:03:35.136081

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "744e7e0a3943"
down_revision: Union[str, None] = "7f1375646d8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_type = sa.Enum("editing", "active", "inactive", name="status")
new_type = sa.Enum("draft", "published", "archived", name="status")
tmp_type = sa.Enum("draft", "published", "archived", name="_status")


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        "post",
        "status",
        existing_type=old_type,
        type_=tmp_type,
        postgresql_using="status::text::_status",
    )
    # old_type.drop(op.get_bind(), checkfirst=False)
    op.execute("DROP TYPE status CASCADE")
    new_type.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        "post",
        "status",
        existing_type=tmp_type,
        type_=new_type,
        postgresql_using="status::text::status",
    )
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        "post",
        "status",
        existing_type=new_type,
        type_=tmp_type,
        postgresql_using="status::text::_status",
    )
    op.execute("DROP TYPE status CASCADE")
    old_type.create(op.get_bind())
    op.alter_column(
        "post",
        "status",
        existing_type=tmp_type,
        type_=old_type,
        postgresql_using="status::text::status",
    )
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
