"""add comming soon to posts

Revision ID: 7f1375646d8b
Revises: 242ec8b54c4f
Create Date: 2023-11-25 12:26:04.637015

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f1375646d8b"
down_revision: Union[str, None] = "242ec8b54c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("coming_soon", sa.Boolean(), nullable=True, default=False)
    )
    op.execute("UPDATE project SET coming_soon = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "coming_soon")
    # ### end Alembic commands ###
