name: Deploy to production
run-name: Deploy ${{ github.repository }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
  workflow_dispatch:
    paths-ignore:
      - 'terraform/**'

env:
  python-version: '3.11'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Install deps
        run: pdm sync
      - name: Setup env file
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          echo JWT_SECRET=$JWT_SECRET >> .env
          echo AWS_S3_BUCKET=$AWS_S3_BUCKET >> .env
          echo DATABASE_URI=$DATABASE_URI >> .env
      - name: Run migrations
        run: pdm run db_upgrade
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: yurb.dev
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Redeploy ECS Service
        run: |
          aws ecs update-service --cluster ${{ secrets.AWS_CLUSTER_NAME }} --service ${{ secrets.AWS_SERVICE_NAME }} --force-new-deployment