name: Deploy to production - GCP
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
  workflow_dispatch:
    paths-ignore:
      - 'terraform/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-west1
  SERVICE_NAME: yurback
  PORT: 8910
  NUM_INSTANCES: 1

jobs:
  deploy:
    if: false
    name: Deploy Yurback to Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Setup gcloud project
        run: gcloud config set project $PROJECT_ID

      - name: Setup Environment
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          echo ENVIRONMENT=production >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          echo DATABASE_URI=$DATABASE_URI >> .env

      - name: Run migrations
        run: pdm run db_upgrade

      - name: Build and push container image
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy container image to Cloud Run
        run: |
          gcloud beta run deploy $SERVICE_NAME \
            --memory 1Gi \
            --execution-environment gen2 \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --port $PORT \
            --project $PROJECT_ID \
            --region $REGION \
            --max-instances $NUM_INSTANCES \
            --min-instances $NUM_INSTANCES \
            --allow-unauthenticated
